# Generated by Django 5.0.4 on 2024-04-16 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="position",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="tasks.position"),
        ),
    ]
