# Generated by Django 5.0.4 on 2024-04-17 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_worker_position"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="is_completed",
        ),
        migrations.AddField(
            model_name="worker",
            name="tasks",
            field=models.ManyToManyField(related_name="workers", to="tasks.task"),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(choices=[("High", "High"), ("Medium", "Medium"), ("Low", "Low")], default="Medium", max_length=10),
        ),
        migrations.AlterField(
            model_name="worker",
            name="position",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tasks.position"),
        ),
    ]
