# Generated by Django 4.2.11 on 2024-04-17 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_worker_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(choices=[("H", "High"), ("M", "Medium"), ("L", "Low")], default="M", max_length=10),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(choices=[("TD", "To do"), ("DG", "Doing"), ("DE", "Done")], default="TD", max_length=10),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="tasks", to="tasks.tasktype"),
        ),
    ]
