# Generated by Django 4.2.11 on 2024-04-21 12:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_alter_task_priority_alter_task_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="invitation_code",
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
