# Generated by Django 4.2.11 on 2024-04-22 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_project_invitation_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ("name",)},
        ),
        migrations.AlterField(
            model_name="chat",
            name="project",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="chat", to="tasks.project"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="chat",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="tasks.chat"),
        ),
    ]
