# Generated by Django 4.2.11 on 2024-04-22 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_alter_project_options_alter_chat_project_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="project",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="chat",
        ),
        migrations.AddField(
            model_name="chat",
            name="messages",
            field=models.ManyToManyField(related_name="chats", to="tasks.chatmessage"),
        ),
        migrations.AddField(
            model_name="project",
            name="chat",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name="projects_chat", to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
