# Generated by Django 4.2.11 on 2024-04-22 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0008_remove_chat_project_remove_chatmessage_chat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="chat",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="projects_chat", to="tasks.chat"),
        ),
    ]
