# Generated by Django 4.2.11 on 2024-04-23 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0009_alter_project_chat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="chat",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="projects_chat", to="tasks.chat"),
        ),
    ]
