# Generated by Django 4.2.11 on 2024-04-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0010_alter_project_chat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="chat",
        ),
        migrations.AddField(
            model_name="project",
            name="messages",
            field=models.ManyToManyField(related_name="chats", to="tasks.chatmessage"),
        ),
        migrations.DeleteModel(
            name="Chat",
        ),
    ]
