# Generated by Django 4.2.11 on 2024-04-29 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0013_alter_project_invitation_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ("title",)},
        ),
        migrations.RenameField(
            model_name="project",
            old_name="name",
            new_name="title",
        ),
    ]
