# Generated by Django 4.2.11 on 2024-04-29 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0014_alter_project_options_rename_name_project_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worker",
            name="tasks",
        ),
        migrations.AddField(
            model_name="task",
            name="creator",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
