# Generated by Django 4.2.11 on 2024-04-30 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0015_remove_worker_tasks_task_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="project",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="tasks.project"),
        ),
    ]
