# Generated by Django 4.2.11 on 2024-05-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0016_task_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(choices=[("High", "High"), ("Medium", "Medium"), ("L", "Low")], default="Medium", max_length=10),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(choices=[("To do", "To do"), ("Doing", "Doing"), ("Done", "Done")], default="To do", max_length=10),
        ),
    ]
