# Generated by Django 4.2.11 on 2024-05-06 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0017_alter_task_priority_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskcomment",
            name="task",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="tasks.task"),
        ),
    ]
