# Generated by Django 4.2.11 on 2024-05-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0019_alter_task_priority"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskcomment",
            options={"ordering": ("-date",)},
        ),
        migrations.AddField(
            model_name="task",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
