# Generated by Django 4.2.11 on 2024-05-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0021_worker_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="profile_image",
            field=models.ImageField(blank=True, upload_to="profile_pictures"),
        ),
    ]
