# Generated by Django 4.2.11 on 2024-05-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0022_alter_worker_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
    ]
